name: PlayTime
author: TechnicallyCoded
authors: [ TechnicallyCoded ]
version: ${project.version}
description: Track player playtime statistics
main: com.tcoded.PlayTime
depend: [ PlaceholderAPI ]

commands:
  playtime:
    description: Primary command
